// <auto-generated />
using System;
using Herald.Core.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Herald.Core.Infrastructure.Migrations
{
    [DbContext(typeof(HeraldDbContext))]
    [Migration("20230201204225_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Herald.Core.Domain.Entities.Guilds.GuildEntity", b =>
                {
                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("Joined")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("JoinedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LeftOn")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("OwnerId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds", (string)null);
                });

            modelBuilder.Entity("Herald.Core.Domain.Entities.Soundtracks.QueueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.ToTable("Queues", (string)null);
                });

            modelBuilder.Entity("Herald.Core.Domain.ValueObjects.Modules.HeraldModule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GuildId");

                    b.ToTable("GuildModules", (string)null);
                });

            modelBuilder.Entity("Herald.Core.Domain.ValueObjects.Soundtracks.QueuedTrackValue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("varchar(160)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<string>("Encoded")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool>("Livestream")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong>("NotifyChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<long?>("QueueId")
                        .HasColumnType("bigint");

                    b.Property<ulong>("RequestUserId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("Seekable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StatusReason")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("QueueId");

                    b.ToTable("QueuedTracks", (string)null);
                });

            modelBuilder.Entity("Herald.Core.Domain.ValueObjects.Modules.HeraldModule", b =>
                {
                    b.HasOne("Herald.Core.Domain.Entities.Guilds.GuildEntity", null)
                        .WithMany("Modules")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Herald.Core.Domain.ValueObjects.Soundtracks.QueuedTrackValue", b =>
                {
                    b.HasOne("Herald.Core.Domain.Entities.Soundtracks.QueueEntity", null)
                        .WithMany("Tracks")
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Herald.Core.Domain.Entities.Guilds.GuildEntity", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("Herald.Core.Domain.Entities.Soundtracks.QueueEntity", b =>
                {
                    b.Navigation("Tracks");
                });
#pragma warning restore 612, 618
        }
    }
}
